## test config file for bulk RNA seq pipeline!

raw_seq_in: 'rp_bulkRNAseq'
metadata_file: 'metadata.tsv'
align_to_fasta: '/scratch/alpine/mapgar@xsede.org/outside_rna_seq_refs/human/hg38.p14.fa'
align_to_gtf: '/scratch/alpine/mapgar@xsede.org/outside_rna_seq_refs/human/hg38.refGene.gtf'
gtf_annot_col: 'gene_id'
align_to_name: 'hg38.p14'
## default is 0, pipeline will infer actual read length with input of 0, if the input is greater than 0, will use the input value (user determined)
raw_seq_read_length: 0
picard_refFlat: '/scratch/alpine/mapgar@xsede.org/outside_rna_seq_refs/human/hg38_refFlat.txt' ## had to copy to another directory bc permission reasons 
picard_rrna_interval_list: '/scratch/alpine/mapgar@xsede.org/outside_rna_seq_refs/human/hg38_GRCh38_rrna_interval_list.txt'
## have for every software except for fastqc and multiqc
cutadapt_params: ''
## use --sjdbGTFtagExonParentGene gene_name flag when using gencode comprehensive genomes!
star_params: '--outSAMunmapped Within KeepPairs --outReadsUnmapped Fastx --outFilterScoreMinOverLread 0.20 --outFilterMatchNminOverLread 0.20'
rsem_params: ' '