## global profile
## the global profile is meant to be used to define default options for a particular environment, 
## like the default cluster submission command or the default number of jobs to run in parallel
## set via the --profile flag in the snakemake command
executor: slurm
latency-wait: 5
default-storage-provider: fs
shared-fs-usage:
  - persistence
  - software-deployment
  - sources
  - source-cache
remote-job-local-storage-prefix: "<your node local storage prefix>"
local-storage-prefix: "<your local storage prefix, for example on login nodes>"